ObservationType.find_or_create_by_name(:name => 'Soil Preparation')
ObservationType.find_or_create_by_name(:name => 'Harvest')
ObservationType.find_or_create_by_name(:name => 'Planting')
ObservationType.find_or_create_by_name(:name => 'Fertilizer application')
ObservationType.find_or_create_by_name(:name => 'Pesticide application')
ObservationType.find_or_create_by_name(:name => 'Herbicide application')
