Study.find_or_create_by(name: 'T', description: 'MAIN')
Study.find_or_create_by(:name => 'B', :description => 'Biodiversity')
Study.find_or_create_by(:name => 'F', :description => 'Fertility Gradient')
Study.find_or_create_by(:name => 'IF', :description => 'Irrigated Fertility Gradient')
Study.find_or_create_by(:name => 'RT', :description => 'Rotation Entry Point')
Study.find_or_create_by(:name => 'G', :description => 'GLBRC')
Study.find_or_create_by(:name => 'CE', :description => 'CES')
Study.find_or_create_by(:name=>'ECB')
Study.find_or_create_by(:name=>'LYSIMETER_FIELD')
Study.find_or_create_by(:name => 'WICST')
