# This configuration was used Ebert to review the kf8a/aglog repository
# on db86a862b2e7e30b3beec708d63c50471c33f59b.
# You can make this the default configuration for future reviews by moving this
# file to your repository as `.ebert.yml` and pushing it to GitHub, and tweak
# it as you wish - To know more on how to change this file to better review your
# repository you can go to https://ebertapp.io/docs/config and see the configuration
# details.
---
styleguide: kf8a/linters
engines:
  phan:
    enabled: true
  reek:
    enabled: true
  fixme:
    enabled: true
  phpmd:
    enabled: true
  eslint:
    enabled: true
  csslint:
    enabled: true
  rubocop:
    enabled: true
  brakeman:
    enabled: true
  coffeelint:
    enabled: true
  duplication:
    config:
      languages:
      - ruby
    enabled: true
  remark-lint:
    enabled: true
  bundler-audit:
    enabled: true
exclude_paths:
- config
- db
- features
- public
- script
- spec
- test
- vendor
- app/assets/javascripts/jquery.tokeninput.js
- app/assets/stylesheets/jquery-ui-1.8.13.custom.css
- app/assets/stylesheets/token-input-facebook.css
 - app/assets/stylesheets/token-input-mac.css
