---
styleguide: kf8a/linters
engines:
  phan:
    enabled: true
  reek:
    enabled: true
  fixme:
    enabled: true
  phpmd:
    enabled: true
  eslint:
    enabled: true
  csslint:
    enabled: true
  rubocop:
    enabled: true
  brakeman:
    enabled: true
    channel: :latest
  coffeelint:
    enabled: true
  duplication:
    config:
      languages:
      - ruby
    enabled: true
  remark-lint:
    enabled: true
  bundler-audit:
    enabled: true
exclude_paths:
- config
- db
- features
- public
- script
- spec
- test
- vendor
